# Generated by Django 5.0.4 on 2024-04-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YumHub", "0004_rename_ordered_at_order_created_at_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish", name="quantity", field=models.PositiveIntegerField(),
        ),
    ]
