# Generated by Django 5.0.4 on 2024-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YumHub", "0006_alter_dish_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
