# Generated by Django 5.0.4 on 2024-04-21 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YumHub", "0007_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
